LTO_ENABLE = yes
TOP_SYMBOLS = yes
MAGIC_ENABLE = no
COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
UNICODE_COMMON = yes
GRAVE_ESC_ENABLE = no
EXTRAKEY_ENABLE = yes
BOOTMAGIC_ENABLE = yes
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
SPACE_CADET_ENABLE = no
AUTOCORRECT_ENABLE = yes
MOUSE_JIGGLE_ENABLE = yes
CUSTOM_TAP_CODE_ENABLE = no
DEBOUNCE_TYPE = asym_eager_defer_pk
AVR_CFLAGS += -mrelax
INTROSPECTION_KEYMAP_C = jack.c

SRC += tapping.c

ifeq ($(strip $(OLED_ENABLE)), yes)
	SRC += oled.c
	WPM_ENABLE = yes
endif

ifeq ($(strip $(RGB_MATRIX_ENABLE)), yes)
	RGB_MATRIX_CUSTOM_USER = yes
	SRC += color.c
endif

ifeq ($(strip $(UNICODE_COMMON)), yes)
	UNICODE_ENABLE = no
	SRC += unicode.c
endif

ifeq ($(strip $(CUSTOM_TAP_CODE_ENABLE)), yes)
	OPT_DEFS += -DCUSTOM_TAP_CODE_ENABLE
	SRC += tap_code.c
endif

ifeq ($(PLATFORM), CHIBIOS)
	ifeq ($(MCU_SERIES), RP2040)
		RP2040_MATH_IN_ROM = no
	endif
	EXTRAFLAGS += -O3
endif

ifeq ($(strip $(RP2040_MATH_IN_ROM)), yes)
	OPT_DEFS += -DRP2040_MATH_IN_ROM
	MCU_LDSCRIPT = RP2040_FLASH_TIMECRIT_ROM_MATH
endif

ifeq ($(strip $(MOUSE_JIGGLE_ENABLE)), yes)
	OPT_DEFS += -DMOUSE_JIGGLE_ENABLE
	MOUSEKEY_ENABLE = yes
	DEFERRED_EXEC_ENABLE = yes
endif
