// Copyright 2026 jack_all@pngu.org
// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#define RGBLIGHT_DEFAULT_HUE 104

#undef RGBLIGHT_MODE_ALTERNATING
#undef RGBLIGHT_MODE_BREATHING
#undef RGBLIGHT_MODE_CHRISTMAS
#undef RGBLIGHT_MODE_KNIGHT
#undef RGBLIGHT_MODE_RAINBOW_MOOD
#undef RGBLIGHT_MODE_RAINBOW_SWIRL
#undef RGBLIGHT_MODE_RGB_TEST
#undef RGBLIGHT_MODE_SNAKE
#undef RGBLIGHT_MODE_STATIC_GRADIENT
#undef RGBLIGHT_MODE_TWINKLE
