// Copyright 2022 jack (@waffle87)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#define WPM_GRAPH
#define I2C_DRIVER I2CD1
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define CIRQUE_PINNACLE_CURVED_OVERLAY
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
#define CIRQUE_PINNACLE_DIAMETER_MM 35
#define SPLIT_WATCHDOG_ENABLE
#define CRC8_USE_TABLE
#define CRC8_OPTIMIZE_SPEED
#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE
#define RGBLIGHT_SLEEP
#define RGBLIGHT_HUE_STEP 5
#define RGBLIGHT_SAT_STEP 5
#endif
