// Copyright 2022 jack (@waffle87)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#define WPM_GRAPH
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define CIRQUE_PINNACLE_CURVED_OVERLAY
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
#define CIRQUE_PINNACLE_DIAMETER_MM 35
#define SPLIT_WATCHDOG_ENABLE
#define CRC8_USE_TABLE
#define CRC8_OPTIMIZE_SPEED
#define ENABLE_RGB_MATRIX_BAND_SAT
#define ENABLE_RGB_MATRIX_RAINDROPS
#define I2C1_CLOCK_SPEED 1000000
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
