// Copyright 2025 jack@pngu.org
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define WS2812_PWM_DRIVER PWMD17
#define WS2812_PWM_CHANNEL 1
#define WS2812_PWM_PAL_MODE 10
#define WS2812_PWM_DMA_STREAM STM32_DMA1_STREAM1
#define WS2812_PWM_DMA_CHANNEL 1
#define WS2812_PWM_DMAMUX_ID STM32_DMAMUX1_TIM17_UP

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN A5
#define SPI_SCK_PAL_MODE 5
#define SPI_MOSI_PIN A7
#define SPI_MOSI_PAL_MODE 5
#define SPI_MISO_PIN A6
#define SPI_MISO_PAL_MODE 5

#define I2C1_SDA_PIN B8
#define I2C1_SCL_PIN B9

#define EXTERNAL_FLASH_SPI_MODE 0
#define EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN B10
#define EXTERNAL_FLASH_SPI_CLOCK_DIVISOR 4
#define EXTERNAL_FLASH_SIZE (16 * 1024 * 1024)

#define MATRIX_COLS 7
#define MATRIX_ROWS 5
#define SHIFT_REG_CS_PIN A3
#define SHIFT_REG_SPI_DIVISOR 8
#define MATRIX_ROW_PINS {B3, A15, A1, B7, B6}
